import type { NextConfig } from "next";

const API_BASE = process.env.API_BASE || "http://127.0.0.1:3001";

const nextConfig: NextConfig = {
  // WordPress permalinks are /%postname%/ — the trailing slash is part of the
  // URL we must preserve. This serves /slug/ canonically and 308s /slug -> /slug/.
  trailingSlash: true,

  // Self-contained server bundle for the Docker image (.next/standalone).
  output: "standalone",

  // Serve the SEO XML (generated by Rails) at the public domain paths.
  async rewrites() {
    return [
      { source: "/sitemap.xml", destination: `${API_BASE}/api/v1/sitemap` },
      { source: "/sitemap-articles-:page.xml", destination: `${API_BASE}/api/v1/sitemap/articles/:page` },
      { source: "/news-sitemap.xml", destination: `${API_BASE}/api/v1/sitemap/news` },
      { source: "/archives-sitemap.xml", destination: `${API_BASE}/api/v1/sitemap/archives` },
      // /feed needs the trailing slash because trailingSlash:true is on.
      { source: "/feed/", destination: `${API_BASE}/api/v1/feed` },
      // Ad click tracking — counts then redirects to the creative's target.
      { source: "/ad/:id/click", destination: `${API_BASE}/api/v1/ads/:id/click` },
      // Article view beacon — browser POSTs here; proxied to the API counter.
      { source: "/track/view/:slug", destination: `${API_BASE}/api/v1/articles/:slug/view` },
    ];
  },
};

export default nextConfig;
