import type { NextConfig } from "next";

// NOTE: read at BUILD time — rewrites are compiled into the build output. The
// Docker image sets it via a build arg (see web/Dockerfile).
const API_BASE = process.env.API_BASE || "http://127.0.0.1:3001";

const nextConfig: NextConfig = {
  // WordPress permalinks are /%postname%/ — the trailing slash is part of the
  // URL we must preserve. This serves /slug/ canonically and 308s /slug -> /slug/.
  trailingSlash: true,

  // Self-contained server bundle for the Docker image (.next/standalone).
  output: "standalone",

  // Fixed 301s the live site already performs (or that fold a duplicate page
  // into its real URL). Data-driven redirects live in the Rails Redirect table.
  async redirects() {
    const moved = (source: string, destination: string) => ({ source, destination, statusCode: 301 as const });
    return [
      moved("/author/:slug", "/writers/:slug/"), // live: /author/x/ → /writers/x/
      moved("/contact", "/contact-us/"), // live does the same
      moved("/subscribe-2", "/subscribe/"), // live does the same
      moved("/privacy-policy-2", "/privacy-policy/"), // live does the same
      moved("/directory-2", "/directory/"), // duplicate hub page on live
    ];
  },

  // Serve the SEO XML (generated by Rails) at the public domain paths.
  async rewrites() {
    return [
      { source: "/sitemap.xml", destination: `${API_BASE}/api/v1/sitemap` },
      { source: "/sitemap-articles-:page.xml", destination: `${API_BASE}/api/v1/sitemap/articles/:page` },
      { source: "/news-sitemap.xml", destination: `${API_BASE}/api/v1/sitemap/news` },
      { source: "/archives-sitemap.xml", destination: `${API_BASE}/api/v1/sitemap/archives` },
      // /feed needs the trailing slash because trailingSlash:true is on.
      { source: "/feed/", destination: `${API_BASE}/api/v1/feed` },
      // Ad click tracking — counts then redirects to the creative's target.
      { source: "/ad/:id/click", destination: `${API_BASE}/api/v1/ads/:id/click` },
      // Ad viewable-impression beacon.
      { source: "/ad/:id/impression", destination: `${API_BASE}/api/v1/ads/:id/impression` },
      // Free registration-wall / newsletter signup.
      { source: "/api/subscribe", destination: `${API_BASE}/api/v1/subscribe` },
      // Article view beacon — browser POSTs here; proxied to the API counter.
      { source: "/track/view/:slug", destination: `${API_BASE}/api/v1/articles/:slug/view` },
    ];
  },
};

export default nextConfig;
